[package]
name = "calc_w1_fin"
version = "0.1.0"
authors = ["trevorschirra"]
edition = "2018"

[lib]
name = "calc_2"
path = "src/main.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
