name: Rust

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ndk
      run: cargo install cargo-ndk
    - name: Set NDK path
      run: echo "ANDROID_NDK_HOME=/home/runner/.cargo/bin/cargo-ndk" >> $GITHUB_ENV
    - name: Add targets
      run: rustup target add x86_64-linux-android
    - name: Build
      run: cargo ndk --platform 21 --target x86_64-linux-android build --verbose
