name: Rust

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Install ndk
      run: cargo install cargo-ndk
    - name: Set NDK path
      run: echo "ANDROID_NDK_HOME=/home/runner/.cargo/bin/cargo-ndk" >> $GITHUB_ENV
    - name: Add targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android 
    - name: Configure python
      run: ./configure --build=x86_64-pc-linux-gnu --host=i686-pc-linux-gnu
    - name: Build
      run: cargo ndk --platform 21 --target x86_64-linux-android build --verbose
