name: Rust

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: 21
    - name: Add targets
      run: rustup target add i686-linux-android
    - name: Build
      run: cargo ndk --platform 21 --target i686-linux-android build --verbose
